// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsjklbekqyhzqbabizve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzamtsYmVrcXloenFiYWJpenZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODE1NDYsImV4cCI6MjA2ODg1NzU0Nn0.0OT9g-P8fXhyj1Y190eNbJgd9q-M-I7FEDjMmOdqHLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});